[file]
recent = [ "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-60\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-59\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-58\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-57\\test_file0\\new.qsst", "C:\\Users\\lei\\AppData\\Local\\Temp\\pytest-of-lei\\pytest-56\\test_file0\\new.qsst", "data/default.qss",]
recentcount = 8

[editor]
fontsize = 11

[general]
language = ""
